/**
 * Copyright (c) 2010 Yahoo! Inc. All rights reserved.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You
 * may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License. See accompanying
 * LICENSE file.
 */

package com.yahoo.ycsb.generator;

import java.util.concurrent.ThreadLocalRandom;


/**
 * Generates a random IP (represented as a 4 bytes array)
 */
public class UniformLongGenerator extends NumberGenerator {
    private Long _lastvalue;

    public UniformLongGenerator() {
        _lastvalue = null;
    }

    /**
     * Generate the next IP in the distribution.
     */
    @Override
    public Long nextValue() {        
        Long ret = ThreadLocalRandom.current().nextLong(2 * (long) Integer.MAX_VALUE);
        setLastValue(ret);

        return ret;
    }

    /**
     * Return the previous array generated by the distribution;
     */
    @Override
    public Long lastValue() {
        if (_lastvalue == null) {
            _lastvalue = nextValue();
        }
        return _lastvalue;
    }

    @Override
    public double mean() {
        return 0;
    }
}
